#!/usr/bin/env sh
X="$(xrandr | grep '*' | uniq | awk '{print$1}' | cut -d 'x' -f1)"  # your horizontal screen resolution
Y="$(xrandr | grep '*' | uniq | awk '{print$1}' | cut -d 'x' -f2)"  # your vertical screen resolution
XP="$(xdotool getmouselocation | awk '{print$1}' | sed 's/x://g')" #mouse coordinate X
YP="$(xdotool getmouselocation | awk '{print$2}' | sed 's/y://g')" #mouse coordinate Y

# BOTTOM BAR
# y=$(($Y-(995/1000*$Y))) # y offset from y resolution; current is 99.5% of Y resolution;

# TOP BAR
 y=$(($Y*3/1000))  # y offser from y resolution; current is 0.3% of Y resolution; comment above line and uncomment this line to use TOP BAR

## right for systray ; add your tray app [stalonetray OR trayer; below is trayer command]
# alignment is always to right by default; change to left if you need
w_mgr="$(wmctrl -m | grep Name:| awk '{print $NF}')"
if [ "$w_mgr" != "dwm" ];then # non EWMH compliant
	
	if [ $y -lt 40 ]; then
		edge="top"
		else
		edge="bottom"
	fi
alfa="0" #set your trayer bg alpha value [ 0 is opaque; to 255 full transparent ]
dock="true" # XMonad has to set trayer in Dock mode else its visibleonly on the first workspace
trayer --edge $edge --align right --distancefrom right --distance 5 \
 --widthtype request --heighttype pixel --height 18 \
 --transparent true --alpha $alfa --tint 0x111827 \
 --SetDockType $dock \
 --padding 2 --margin 1 --iconspacing 4 --expand false
fi &
sleep 3 && ~/.xmonad/dzenstatusBar &&
sleep 5 && ~/.xmonad/dzenTitleBar &
sleep 7 && ~/.xmonad/dzenExitButton &
## deps for workspace and forecast
location="Vapi" ## TYPE YOUR CITY NAME WITHIN QUOTES
sleep 5 && sh ~/.bin/dzenworkspaces.sh &
sleep 15 && if [ "$(wmctrl -d | sed -n '/* /s///p' | awk '{print$NF}')" = " " ];then echo " " > /tmp/AWS;fi &
while : ;do curl -s 'http://v1.wttr.in/$location\?MT' | tail -n33 | head -n30 > /tmp/asciiwttr;sleep 1801;done
