#!/usr/bin/env sh
# 
# Dzen2 App Launcher script box version by Rasmus Edgar.
# -tw = Width of titlebar, -w = Width of slavewindow,
# -l = length of slavewindow. Remember to adjust -l accordingly when adding 
# apps. ^pa(*) is for text/decoration alignment.
# 
#
#
# Menu script starts below.   
#

# Needed Applications:

AP1=firefox
AP2=sakura
AP3=gimp
AP4=gedit
AP5=pcmanfm
SM1=rofi-exit-menu

# Get cursor position:

X=$(xrandr | grep '*' | uniq | awk '{print$1}' | cut -d 'x' -f1) #screen resolution ; X
Y=$(xrandr | grep '*' | uniq | awk '{print$1}' | cut -d 'x' -f2) #screen resolution Y
XP="$(xdotool getmouselocation | awk '{print$1}' | sed 's/x://g')"
YP="$(xdotool getmouselocation | awk '{print$2}' | sed 's/y://g')"
if [ "$YP" -lt "50" ];then loc="1";else 
	loc="7";fi &&
if [ $loc = "1" ];then anc="1";elif
	[ $loc = "7" ]; then anc="7"
fi &&

if [ $loc = "1" ]; then pY=$(($YP+10));else
		pY=$(($YP-$Y))
fi &&

if [ $(($X-$XP+10)) -lt $menu_width ];then
	pX=$(($XP-$menu_width));else
	pX=$((XP+5))
fi

# Decorations for the menu:

DC1=1x18
DC2=3x2
DC3=4x2
DC4=3x1
DC5=198x12
DC6=199x18

# Font:

#FONT="-*-dina-medium-r-*-*-15-*-*-*-*-*-iso8859-1"
FONT="pretzel-13:antialias=true"
# Menu Title

TI=" Easy access "

# Colors:

FG1=#93c572
FG2=#f57900
FG3=#93c572
#FG3=#D9A509
BG1=#0a0e11

# Icons:

IC1=~/.xmonad/simply-xbm/firefox.xbm
IC2=~/.xmonad/simply-xbm/urxvt.xbm
IC3=~/.xmonad/simply-xbm/gimp.xbm
IC4=~/.xmonad/simply-xbm/gedit.xbm
IC5=~/.xmonad/simply-xbm/pcmanfm.xbm
SMI=~/.xmonad/simply-xbm/arrow-right.xbm

# Text piped to Dzen2

(echo "^ro(${DC6})^ib(1)^pa(30)$TI" ;echo -e "^fg(${FG1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC1})^fg(${FG1}) ${AP1} ^pa(192)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC2})^fg(${FG1}) ${AP2} ^pa(192)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC3})^fg(${FG1}) ${AP3} ^pa(192)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC4})^fg(${FG1}) ${AP4} ^pa(192)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC5})^fg(${FG1}) ${AP5} ^pa(192)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${SMI})^fg(${FG1}) ${SM1} ^pa(192)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^ro(${DC6})^ib(1)^pa(2)favourites")\
| (dzen2 -y "$pY" -x "$pX" -fn "$FONT" -bg "$BG1" -fg "$FG1" -l 7 -tw 200 -ta l -w 200 -m -p -e 'onstart=uncollapse;button1=menuexec;leaveslave=exit;button3=exit')
