#!/usr/bin/env sh

rofimenu_cmd() {
menu_width="$1"
X=$(xrandr | grep '*' | uniq | awk '{print$1}' | cut -d 'x' -f1) #screen resolution ; X
Y=$(xrandr | grep '*' | uniq | awk '{print$1}' | cut -d 'x' -f2) #screen resolution Y
XP="$(xdotool getmouselocation | awk '{print$1}' | sed 's/x://g')"
YP="$(xdotool getmouselocation | awk '{print$2}' | sed 's/y://g')"

if [ $YP -le "$(($Y*5/10))" ]; then
loc=1; else loc="7"
fi &&
if [ $loc = "1" ]; then
	anc="1";else
	anc="7"
fi

if [ $YP -le "$(($Y*5/10))" ]; then
	pY=$(($pY+10)); else
	pY=$(($YP-$Y))
fi  # Y offset

if [ $(($X-$XP)) -le $(($menu_width +10)) ]; then
	pX=$(($XP-$menu_width));else
	pX=$(($XP+5))
fi # X offset

	rofi -show "drun" \
		-modi "drun" \
		-location $loc -anchor $anc \
		-xoffset $pX -yoffset $pY \
		-no-sidebar-mode \
 		-theme-str "#window { width: 33%; }" \
		-theme-str "#listview { lines: 9; dynamic: true; fixed-height: false; }"
#	 rofimenu
}
rofimenu_cmd
